version: '3'

volumes:
  cache:
    driver: local
  db-data:
    driver: local

services:
  app:
    build:
      context: .
    container_name: currency
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/currency?currentSchema=currency
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - '8080:8080'

  db:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=currency
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-rc-alpine
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass cmVkaXNwYXNzd29yZA==
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d
      - cache:/data


#TODO: Сделать так, чтобы секреты импортировались из .env файла.