spring:

  liquibase:
    change-log: classpath:liquibase/db.changelog.yml
    enabled: true
    default-schema: currency

#  config:
#    import: optional:file:.env[.properties]
  application:
    name: Currency

  #CACHE INFO
  cache:
    type: redis
    cache-names: redis-cache

  #REDIS INFO
  data:
    redis:
      host: localhost
      port: 6379
      password: cmVkaXNwYXNzd29yZA== #Password encoded from base 64 redispassword

  #DATABASE POSTGRESQL CONFIG
  datasource:
    url: jdbc:postgresql://localhost:5432/currency?currentSchema=currency
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  #JWT INFO
security:
  jwt:
    secret: da9583d1078b02d6f400a1710d82b63513b4654b #secretserverkey
    access: 1
    refresh: 30
