spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: Currency

  #CACHE INFO
  cache:
    type: redis
    cache-names: redis-cache

  #REDIS INFO
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD} #Password encoded from base 64 redispassword

  #DATABASE POSTGRESQL CONFIG
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
#  sql:
#    init:
#      mode: always
#      continue-on-error: false
#      data-locations: classpath:demo_data.sql
      
  #JWT INFO
security:
  jwt:
    secret: ${JWT_SECRET} #secretserverkey
    access: 1
    refresh: 30


