spring:

  application:
    name: Currency

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        type: true
        use_sql_comments: true
  kafka:
    admin:
      properties:
        offsets.topic.replication.factor: 1
        transaction.state.log.replication.factor: 1
        transaction.state.log.min.isr: 1
    bootstrap-servers:
      - "kafka:9092"
    topics:
      - name: "payment-command"
        partitions: 1
        replication-factor: 1
      - name: "payment-command-result"
        partitions: 1
        replication-factor: 1

  logging:
    level:
      org.hibernate.type.descriptor.sql: TRACE

  liquibase:
    drop-first: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: currency


  #  config:
#    import: optional:file:.env[.properties]

  #CACHE INFO
  cache:
    type: redis
    cache-names: redis-cache

  #REDIS INFO
  data:
    redis:
      host: redis
      port: 6379
      password: cmVkaXNwYXNzd29yZA== #Password encoded from base 64 redispassword

  #DATABASE POSTGRESQL CONFIG
  datasource:
    url: jdbc:postgresql://localhost:5432/currency?currentSchema=currency
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


  #JWT INFO
security:
  jwt:
    secret: da9583d1078b02d6f400a1710d82b63513b4654b #secretserverkey
    access: 1
    refresh: 30

currencyfreaks:
  api:
    key: 465eadc1dd6e401fbaff4711b73892f8           # забирается из env
    url: https://api.currencyfreaks.com/v2.0/rates/    # базовый URL
